spring.application.name=porject

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

<<<<<<< HEAD
# 'dev' for H2 (local testing)
# 'prod' for PostgreSQL
spring.profiles.active=dev
=======
# Render DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
>>>>>>> origin/main
